export const POST_ACCOUNT_REQUEST = 'POST_ACCOUNT_REQUEST';
export const POST_ACCOUNT_SUCCESS = 'POST_ACCOUNT_SUCCESS';
export const POST_ACCOUNT_FAIL = 'POST_ACCOUNT_FAIL';

export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';

export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';

export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';

export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT';

export const RESET_CART_FAIL = 'RESET_CART_FAIL';
export const RESET_CART_REQUEST = 'RESET_CART_REQUEST';
export const RESET_CART_SUCCESS = 'RESET_CART_SUCCESS';
